# Dialecto de base de datos
# Configuración del Data Source principal


main.datasource.url = jdbc:oracle:thin:@//introckdb210.egara.local:1521/dbscontinsti
main.datasource.username = CONTINST
main.datasource.password =463gt38CGhjri8ccF


# Liquibase
main.liquibase.change-log = com/company/gabinetdealcadia/liquibase/changelog.xml

# UI y otros
jmix.ui.login-view-id = LoginView
jmix.ui.main-view-id = MainView
jmix.ui.menu-config = com/company/gabinetdealcadia/menu.xml
ui.login.defaultUsername = admin
ui.login.defaultPassword = admin

jmix.ldap.enabled=true
jmix.ldap.urls=ldap://10.1.9.12:389
jmix.ldap.base-dn=OU=TERRASSA,DC=egara,DC=local


jmix.ldap.manager-dn=CN=Adm Tossacodi,OU=Cuentas de Servicio,OU=Usuarios Especiales,OU=OTROS,OU=TERRASSA,DC=egara,DC=local
jmix.ldap.manager-password=TerrassaC0d1
jmix.ldap.user-details-source=app
jmix.ldap.synchronize-user-on-login=true

# Active Directory
jmix.ldap.use-active-directory-configuration=true
jmix.ldap.active-directory-domain=egara.local
jmix.ldap.user-search-filter=(&(objectClass=user)(sAMAccountName={1}))