# Dialecto de base de datos
# Configuración del Data Source principal

main.datasource.url = ${DB_URL}
main.datasource.username = ${DB_USER}
main.datasource.password = ${DB_PASSWORD}

# Liquibase
main.liquibase.change-log = com/company/gabinetdealcadia/liquibase/changelog.xml

# UI y otros
jmix.ui.login-view-id = LoginView
jmix.ui.main-view-id = MainView
jmix.ui.menu-config = com/company/gabinetdealcadia/menu.xml
ui.login.defaultUsername = admin
ui.login.defaultPassword = admin

# LDAP / Active Directory
jmix.ldap.enabled=true
jmix.ldap.urls=${LDAP_URL}
jmix.ldap.base-dn=${LDAP_BASE_DN}

jmix.ldap.manager-dn=${LDAP_MANAGER_DN}
jmix.ldap.manager-password=${LDAP_MANAGER_PASSWORD}
jmix.ldap.user-details-source=ldap
jmix.ldap.synchronize-user-on-login=false

# Active Directory
jmix.ldap.use-active-directory-configuration=true
jmix.ldap.active-directory-domain=${LDAP_DOMAIN}
jmix.ldap.user-search-filter=(&(objectClass=user)(sAMAccountName={1}))