# Dialecto de base de datos
# Configuración del Data Source principal


main.datasource.url = jdbc:oracle:thin:@//introckdb210.egara.local:1521/dbscontinsti
main.datasource.username = CONTINST
main.datasource.password =463gt38CGhjri8ccF


# Liquibase
main.liquibase.change-log = com/company/gabinetdealcadia/liquibase/changelog.xml

# UI y otros
jmix.ui.login-view-id = LoginView
jmix.ui.main-view-id = MainView
jmix.ui.menu-config = com/company/gabinetdealcadia/menu.xml
ui.login.defaultUsername = admin
ui.login.defaultPassword = admin